import { Region } from '../models/Region';
import { Country } from '../models/Country';

export const AUSTRALIA_REGIONS_FR = [
  { id: 1, code: 'SA', name: 'Australie-Méridionale' } as Region,
  { id: 2, code: 'WA', name: 'Australie-Occidentale' } as Region,
  { id: 3, code: 'NSW', name: 'Nouvelle-Galles du Sud' } as Region,
  { id: 4, code: 'QLD', name: 'Queensland' } as Region,
  { id: 5, code: 'TAS', name: 'Tasmanie' } as Region,
  { id: 6, code: 'VIC', name: 'Victoria' } as Region,
  {
    id: 7,
    code: 'ACT',
    name: 'Territoire de la capitale Australienne',
  } as Region,
  { id: 8, code: 'NT', name: 'Territoire du Nord' } as Region,
];

export const BRAZIL_REGIONS_FR = [
  { id: 9, code: 'AC', name: 'Acre' } as Region,
  { id: 10, code: 'AL', name: 'Alagoas' } as Region,
  { id: 11, code: 'AP', name: 'Amapá' } as Region,
  { id: 12, code: 'AM', name: 'Amazonas' } as Region,
  { id: 13, code: 'BA', name: 'Bahia' } as Region,
  { id: 14, code: 'CE', name: 'Ceará' } as Region,
  { id: 15, code: 'DF', name: 'District Fédéral' } as Region,
  { id: 16, code: 'ES', name: 'Espírito Santo' } as Region,
  { id: 17, code: 'GO', name: 'Goiás' } as Region,
  { id: 18, code: 'MA', name: 'Maranhão' } as Region,
  { id: 19, code: 'MT', name: 'Mato Grosso' } as Region,
  { id: 20, code: 'MS', name: 'Mato Grosso do Sul' } as Region,
  { id: 21, code: 'MG', name: 'Minas Gerais' } as Region,
  { id: 22, code: 'PA', name: 'Pará' } as Region,
  { id: 23, code: 'PB', name: 'Paraíba' } as Region,
  { id: 24, code: 'PR', name: 'Paraná' } as Region,
  { id: 25, code: 'PE', name: 'Pernambuco' } as Region,
  { id: 26, code: 'PI', name: 'Piauí' } as Region,
  { id: 27, code: 'RJ', name: 'Rio de Janeiro' } as Region,
  { id: 28, code: 'RN', name: 'Rio Grande do Norte' } as Region,
  { id: 29, code: 'RS', name: 'Rio Grande do Sul' } as Region,
  { id: 30, code: 'RO', name: 'Rondônia' } as Region,
  { id: 31, code: 'RR', name: 'Roraima' } as Region,
  { id: 32, code: 'SC', name: 'Santa Catarina' } as Region,
  { id: 33, code: 'SP', name: 'São Paulo' } as Region,
  { id: 34, code: 'SE', name: 'Sergipe' } as Region,
  { id: 35, code: 'TO', name: 'Tocantins' } as Region,
];

export const CANADA_REGIONS_FR = [
  { id: 36, code: 'AB', name: 'Alberta' } as Region,
  { id: 37, code: 'BC', name: 'Colombie-Britannique' } as Region,
  { id: 38, code: 'PE', name: 'Île du Prince Édouard' } as Region,
  { id: 39, code: 'MB', name: 'Manitoba' } as Region,
  { id: 40, code: 'NB', name: 'Nouveau-Brunswick' } as Region,
  { id: 41, code: 'NS', name: 'Nouvelle-Écosse' } as Region,
  { id: 42, code: 'ON', name: 'Ontario' } as Region,
  { id: 43, code: 'QC', name: 'Québec' } as Region,
  { id: 44, code: 'SK', name: 'Saskatchewan' } as Region,
  { id: 45, code: 'NL', name: 'Terre-Neuve et Labrador' } as Region,
  { id: 46, code: 'NU', name: 'Nunavut' } as Region,
  { id: 47, code: 'NT', name: 'Territoires du Nord-Ouest' } as Region,
  { id: 48, code: 'YT', name: 'Yukon' } as Region,
];

export const USA_REGIONS_FR = [
  { id: 49, code: 'NY', name: 'New York' } as Region,
  { id: 50, code: 'CA', name: 'Californie' } as Region,
  { id: 51, code: 'IL', name: 'Illinois' } as Region,
  { id: 52, code: 'TX', name: 'Texas' } as Region,
  { id: 53, code: 'AZ', name: 'Arizona' } as Region,
  { id: 54, code: 'PA', name: 'Pennsylvanie' } as Region,
  { id: 55, code: 'FL', name: 'Floride' } as Region,
  { id: 56, code: 'OH', name: 'Ohio' } as Region,
  { id: 57, code: 'NC', name: 'Caroline du Nord' } as Region,
  { id: 58, code: 'IN', name: 'Indiana' } as Region,
  { id: 59, code: 'WA', name: 'Washington' } as Region,
  { id: 60, code: 'CO', name: 'Colorado' } as Region,
  { id: 61, code: 'D.C.', name: 'District de Colombia' } as Region,
  { id: 62, code: 'MA', name: 'Massachusetts' } as Region,
  { id: 63, code: 'TN', name: 'Tennessee' } as Region,
  { id: 64, code: 'MI', name: 'Michigan' } as Region,
  { id: 65, code: 'OR', name: 'Oregon' } as Region,
  { id: 66, code: 'NV', name: 'Nevada' } as Region,
  { id: 67, code: 'OK', name: 'Oklahoma' } as Region,
  { id: 68, code: 'KY', name: 'Kentucky' } as Region,
  { id: 69, code: 'MD', name: 'Maryland' } as Region,
  { id: 70, code: 'WI', name: 'Wisconsin' } as Region,
  { id: 71, code: 'NM', name: 'Nouveau-Mexique' } as Region,
  { id: 72, code: 'MO', name: 'Missouri' } as Region,
  { id: 73, code: 'GA', name: 'Géorgie' } as Region,
  { id: 74, code: 'NE', name: 'Nebraska' } as Region,
  { id: 75, code: 'VA', name: 'Virginie' } as Region,
  { id: 76, code: 'MN', name: 'Minnesota' } as Region,
  { id: 77, code: 'LA', name: 'Louisiane' } as Region,
  { id: 78, code: 'KS', name: 'Kansas' } as Region,
  { id: 79, code: 'AK', name: 'Alaska' } as Region,
  { id: 80, code: 'NJ', name: 'New Jersey' } as Region,
  { id: 81, code: 'ID', name: 'Idaho' } as Region,
  { id: 82, code: 'IA', name: 'Iowa' } as Region,
  { id: 83, code: 'AL', name: 'Alabama' } as Region,
  { id: 84, code: 'UT', name: 'Utah' } as Region,
  { id: 85, code: 'AR', name: 'Arkansas' } as Region,
  { id: 86, code: 'SD', name: 'Dakota du Sud' } as Region,
  { id: 87, code: 'RI', name: 'Rhode Island' } as Region,
  { id: 88, code: 'MS', name: 'Mississippi' } as Region,
  { id: 89, code: 'CT', name: 'Connecticut' } as Region,
  { id: 90, code: 'SC', name: 'Caroline du Sud' } as Region,
  { id: 91, code: 'ND', name: 'Dakota du Nord' } as Region,
  { id: 92, code: 'MT', name: 'Montana' } as Region,
  { id: 93, code: 'NH', name: 'New Hampshire' } as Region,
  { id: 94, code: 'ME', name: 'Maine' } as Region,
  { id: 95, code: 'WY', name: 'Wyoming' } as Region,
  { id: 96, code: 'WV', name: 'Virginie-Occidentale' } as Region,
  { id: 97, code: 'VT', name: 'Vermont' } as Region,
  { id: 98, code: 'HI', name: 'Hawaii' } as Region,
];

export const COUNTRIES_FR = [
  { id: 1, name: 'Afghanistan', icao: 'YA', flagCode: 'af' } as Country,
  { id: 2, name: 'Afrique du Sud', icao: 'ZS', flagCode: 'za' } as Country,
  { id: 3, name: 'Albanie', icao: 'ZA', flagCode: 'al' } as Country,
  { id: 4, name: 'Algérie', icao: '7T', flagCode: 'dz' } as Country,
  { id: 5, name: 'Allemagne', icao: 'D', flagCode: 'de' } as Country,
  { id: 6, name: 'Angola', icao: 'D2', flagCode: 'ao' } as Country,
  {
    id: 7,
    name: 'Anguilla (Royaume-Uni)',
    icao: 'VP-A',
    flagCode: 'ai',
  } as Country,
  { id: 8, name: 'Antigua-et-Barbuda', icao: 'V2', flagCode: 'ag' } as Country,
  { id: 9, name: 'Arabie Saoudite', icao: 'HZ', flagCode: 'sa' } as Country,
  { id: 10, name: 'Argentine', icao: 'LV', flagCode: 'ar' } as Country,
  { id: 11, name: 'Arménie', icao: 'EK', flagCode: 'am' } as Country,
  { id: 12, name: 'Aruba (Pays-Bas)', icao: 'P4', flagCode: 'aw' } as Country,
  {
    id: 13,
    name: 'Australie',
    icao: 'VH',
    flagCode: 'au',
    regions: AUSTRALIA_REGIONS_FR,
  } as Country,
  { id: 14, name: 'Autriche', icao: 'OE', flagCode: 'at' } as Country,
  { id: 15, name: 'Azerbaïdjan', icao: '4K', flagCode: 'az' } as Country,
  { id: 16, name: 'Bahamas', icao: 'C6', flagCode: 'bs' } as Country,
  { id: 17, name: 'Bahreïn', icao: 'A9C', flagCode: 'bh' } as Country,
  { id: 18, name: 'Bangladesh', icao: 'S2', flagCode: 'bd' } as Country,
  { id: 19, name: 'Barbade', icao: '8P', flagCode: 'bb' } as Country,
  { id: 20, name: 'Belgique', icao: 'OO', flagCode: 'be' } as Country,
  { id: 21, name: 'Bélize', icao: 'V3', flagCode: 'bz' } as Country,
  { id: 22, name: 'Bénin', icao: 'TY', flagCode: 'bj' } as Country,
  {
    id: 23,
    name: 'Bermudes (Royaume-Uni)',
    icao: 'VP-B',
    flagCode: 'bm',
  } as Country,
  { id: 24, name: 'Bhoutan', icao: 'A5', flagCode: 'bt' } as Country,
  { id: 25, name: 'Biélorussie', icao: 'EW', flagCode: 'by' } as Country,
  { id: 26, name: 'Bolivie', icao: 'CP', flagCode: 'bo' } as Country,
  { id: 27, name: 'Bonaire (Pays-Bas)', icao: 'PJ', flagCode: 'bq' } as Country,
  { id: 28, name: 'Bosnie-Herzégovine', icao: 'E7', flagCode: 'ba' } as Country,
  { id: 29, name: 'Botswana', icao: 'A2', flagCode: 'bw' } as Country,
  {
    id: 30,
    name: 'Brésil',
    icao: 'PP',
    flagCode: 'br',
    regions: BRAZIL_REGIONS_FR,
  } as Country,
  { id: 31, name: 'Brunéi Darussalam', icao: 'V8', flagCode: 'bn' } as Country,
  { id: 32, name: 'Bulgarie', icao: 'LZ', flagCode: 'bg' } as Country,
  { id: 33, name: 'Burkina Faso', icao: 'XT', flagCode: 'bf' } as Country,
  { id: 34, name: 'Burundi', icao: '9U', flagCode: 'bi' } as Country,
  { id: 35, name: 'Cambodge', icao: 'XU', flagCode: 'kh' } as Country,
  { id: 36, name: 'Cameroun', icao: 'TJ', flagCode: 'cm' } as Country,
  {
    id: 37,
    name: 'Canada',
    icao: 'C',
    flagCode: 'ca',
    regions: CANADA_REGIONS_FR,
  } as Country,
  { id: 38, name: 'Cap-Vert', icao: 'D4', flagCode: 'cv' } as Country,
  { id: 39, name: 'Chili', icao: 'CC', flagCode: 'cl' } as Country,
  { id: 40, name: 'Chine', icao: 'B', flagCode: 'cn' } as Country,
  { id: 41, name: 'Chypre', icao: '5B', flagCode: 'cy' } as Country,
  { id: 42, name: 'Colombie', icao: 'HK', flagCode: 'co' } as Country,
  { id: 43, name: 'Comores', icao: 'D6', flagCode: 'km' } as Country,
  { id: 44, name: 'Congo', icao: 'TN', flagCode: 'cg' } as Country,
  { id: 45, name: 'Corée du Nord', icao: 'P', flagCode: 'kp' } as Country,
  { id: 46, name: 'Corée du Sud', icao: 'HL', flagCode: 'kr' } as Country,
  { id: 47, name: 'Costa Rica', icao: 'TI', flagCode: 'cr' } as Country,
  { id: 48, name: "Côte d'Ivoire", icao: 'TU', flagCode: 'ci' } as Country,
  { id: 49, name: 'Croatie', icao: '9A', flagCode: 'hr' } as Country,
  { id: 50, name: 'Cuba', icao: 'CU', flagCode: 'cu' } as Country,
  { id: 51, name: 'Curaçao (Pays-Bas)', icao: 'PJ', flagCode: 'cw' } as Country,
  { id: 52, name: 'Danemark', icao: 'OY', flagCode: 'dk' } as Country,
  { id: 53, name: 'Djibouti', icao: 'J2', flagCode: 'dj' } as Country,
  { id: 54, name: 'Dominique', icao: 'J7', flagCode: 'dm' } as Country,
  { id: 55, name: 'Égypte', icao: 'SU', flagCode: 'eg' } as Country,
  {
    id: 56,
    name: 'Émirats arabes unis',
    icao: 'A6',
    flagCode: 'ae',
  } as Country,
  { id: 57, name: 'Équateur', icao: 'HC', flagCode: 'ec' } as Country,
  { id: 58, name: 'Érythrée', icao: 'E3', flagCode: 'er' } as Country,
  { id: 59, name: 'Espagne', icao: 'EC', flagCode: 'es' } as Country,
  { id: 60, name: 'Estonie', icao: 'ES', flagCode: 'ee' } as Country,
  { id: 61, name: 'Eswatini', icao: '3D', flagCode: 'sz' } as Country,
  {
    id: 62,
    name: 'Micronésie (États fédérés de)',
    icao: 'V6',
    flagCode: 'fm',
  } as Country,
  {
    id: 63,
    name: 'États-Unis',
    icao: 'N',
    flagCode: 'us',
    regions: USA_REGIONS_FR,
  } as Country,
  { id: 64, name: 'Éthiopie', icao: 'ET', flagCode: 'et' } as Country,
  { id: 65, name: 'Fidji', icao: 'DQ', flagCode: 'fj' } as Country,
  { id: 66, name: 'Finlande', icao: 'OH', flagCode: 'fi' } as Country,
  { id: 67, name: 'France', icao: 'F', flagCode: 'fr' } as Country,
  { id: 68, name: 'Gabon', icao: 'TR', flagCode: 'ga' } as Country,
  { id: 69, name: 'Gambie', icao: 'C5', flagCode: 'gm' } as Country,
  { id: 70, name: 'Géorgie', icao: '4L', flagCode: 'ge' } as Country,
  { id: 71, name: 'Ghana', icao: '9G', flagCode: 'gh' } as Country,
  {
    id: 72,
    name: 'Gibraltar (Royaume-Uni)',
    icao: 'VP-G',
    flagCode: 'gi',
  } as Country,
  { id: 73, name: 'Grèce', icao: 'SX', flagCode: 'gr' } as Country,
  { id: 74, name: 'Grenade', icao: 'J3', flagCode: 'gd' } as Country,
  {
    id: 75,
    name: 'Groenland (Danemark)',
    icao: 'OY',
    flagCode: 'gl',
  } as Country,
  { id: 76, name: 'Guam (États-Unis)', icao: 'N', flagCode: 'gu' } as Country,
  { id: 77, name: 'Guatémala', icao: 'TG', flagCode: 'gt' } as Country,
  { id: 78, name: 'Guinée', icao: '3X', flagCode: 'gn' } as Country,
  { id: 79, name: 'Guinée équatoriale', icao: '3C', flagCode: 'gq' } as Country,
  { id: 80, name: 'Guinée-Bissau', icao: 'J5', flagCode: 'gw' } as Country,
  { id: 81, name: 'Guyana', icao: 'BR', flagCode: 'gy' } as Country,
  { id: 82, name: 'Haïti', icao: 'HH', flagCode: 'ht' } as Country,
  { id: 83, name: 'Honduras', icao: 'HR', flagCode: 'hn' } as Country,
  { id: 84, name: 'Hong Kong (Chine)', icao: 'B-H', flagCode: 'hk' } as Country,
  { id: 85, name: 'Hongrie', icao: 'HA', flagCode: 'hu' } as Country,
  {
    id: 86,
    name: 'Île Norfolk (Australie)',
    icao: 'VH',
    flagCode: 'nf',
  } as Country,
  {
    id: 87,
    name: 'Îles Caïmans (Royaume-Uni)',
    icao: 'VP-C',
    flagCode: 'ky',
  } as Country,
  {
    id: 88,
    name: 'Îles Cocos (Australie)',
    icao: 'VH',
    flagCode: 'cc',
  } as Country,
  {
    id: 89,
    name: 'Îles Cook (Nouvelle-Zélande)',
    icao: 'E5',
    flagCode: 'ck',
  } as Country,
  {
    id: 90,
    name: 'Îles Féroé (Danemark)',
    icao: 'OY',
    flagCode: 'fo',
  } as Country,
  {
    id: 91,
    name: 'Îles Mariannes du Nord (États-Unis)',
    icao: 'N',
    flagCode: 'mp',
  } as Country,
  { id: 92, name: 'Îles Salomon', icao: 'H4', flagCode: 'sb' } as Country,
  {
    id: 93,
    name: 'Îles Turques-et-Caïques (Royaume-Uni)',
    icao: 'VQ-T',
    flagCode: 'tc',
  } as Country,
  { id: 94, name: 'Inde', icao: 'VT', flagCode: 'in' } as Country,
  { id: 95, name: 'Indonésie', icao: 'PK', flagCode: 'id' } as Country,
  { id: 96, name: 'Irak', icao: 'YI', flagCode: 'iq' } as Country,
  { id: 97, name: 'Iran', icao: 'EP', flagCode: 'ir' } as Country,
  { id: 98, name: 'Irlande', icao: 'EI', flagCode: 'ie' } as Country,
  { id: 99, name: 'Islande', icao: 'TF', flagCode: 'is' } as Country,
  { id: 100, name: 'Israël', icao: '4X', flagCode: 'il' } as Country,
  { id: 101, name: 'Italie', icao: 'I', flagCode: 'it' } as Country,
  { id: 102, name: 'Jamaïque', icao: '6Y', flagCode: 'jm' } as Country,
  { id: 103, name: 'Japon', icao: 'JA', flagCode: 'jp' } as Country,
  { id: 104, name: 'Jordanie', icao: 'JY', flagCode: 'jo' } as Country,
  { id: 105, name: 'Kazakhstan', icao: 'UP', flagCode: 'kz' } as Country,
  { id: 106, name: 'Kenya', icao: '5Y', flagCode: 'ke' } as Country,
  { id: 107, name: 'Kirghizistan', icao: 'EX', flagCode: 'kg' } as Country,
  { id: 108, name: 'Kiribati', icao: 'T3', flagCode: 'ki' } as Country,
  { id: 109, name: 'Kosovo', icao: 'Z6', flagCode: 'xk' } as Country,
  { id: 110, name: 'Koweït', icao: '9K', flagCode: 'kw' } as Country,
  { id: 111, name: 'Laos', icao: 'RDPL', flagCode: 'la' } as Country,
  { id: 112, name: 'Lesotho', icao: '7P', flagCode: 'ls' } as Country,
  { id: 113, name: 'Lettonie', icao: 'YL', flagCode: 'lv' } as Country,
  { id: 114, name: 'Liban', icao: 'OD', flagCode: 'lb' } as Country,
  { id: 115, name: 'Libéria', icao: 'A8', flagCode: 'lr' } as Country,
  { id: 116, name: 'Libye', icao: '5A', flagCode: 'ly' } as Country,
  { id: 117, name: 'Lituanie', icao: 'LY', flagCode: 'lt' } as Country,
  { id: 118, name: 'Luxembourg', icao: 'LX', flagCode: 'lu' } as Country,
  { id: 119, name: 'Macao (Chine)', icao: 'B-M', flagCode: 'mo' } as Country,
  { id: 120, name: 'Macédoine du Nord', icao: 'Z3', flagCode: 'mk' } as Country,
  { id: 121, name: 'Madagascar', icao: '5R', flagCode: 'mg' } as Country,
  { id: 122, name: 'Malaisie', icao: '9M', flagCode: 'my' } as Country,
  { id: 123, name: 'Malawi', icao: '7Q', flagCode: 'mw' } as Country,
  { id: 124, name: 'Maldives', icao: '8Q', flagCode: 'mv' } as Country,
  { id: 125, name: 'Mali', icao: 'TZ', flagCode: 'ml' } as Country,
  { id: 126, name: 'Malte', icao: '9H', flagCode: 'mt' } as Country,
  { id: 127, name: 'Maroc', icao: 'CN', flagCode: 'ma' } as Country,
  { id: 128, name: 'Île Maurice', icao: '3B', flagCode: 'mu' } as Country,
  { id: 129, name: 'Mauritanie', icao: '5T', flagCode: 'mr' } as Country,
  { id: 130, name: 'Mexique', icao: 'XA', flagCode: 'mx' } as Country,
  { id: 131, name: 'Moldavie', icao: 'ER', flagCode: 'md' } as Country,
  { id: 132, name: 'Mongolie', icao: 'JU', flagCode: 'mn' } as Country,
  { id: 133, name: 'Monténégro', icao: '4O', flagCode: 'me' } as Country,
  { id: 134, name: 'Mozambique', icao: 'C9', flagCode: 'mz' } as Country,
  { id: 135, name: 'Myanmar', icao: 'XY', flagCode: 'mm' } as Country,
  { id: 136, name: 'Namibie', icao: 'V5', flagCode: 'na' } as Country,
  { id: 137, name: 'Nauru', icao: 'C2', flagCode: 'nr' } as Country,
  { id: 138, name: 'Népal', icao: '9N', flagCode: 'np' } as Country,
  { id: 139, name: 'Nicaragua', icao: 'YN', flagCode: 'ni' } as Country,
  { id: 140, name: 'Niger', icao: '5U', flagCode: 'ne' } as Country,
  { id: 141, name: 'Nigéria', icao: '5N', flagCode: 'ng' } as Country,
  {
    id: 142,
    name: 'Niue (Nouvelle-Zélande)',
    icao: 'ZK',
    flagCode: 'nu',
  } as Country,
  { id: 143, name: 'Norvège', icao: 'LN', flagCode: 'no' } as Country,
  { id: 144, name: 'Nouvelle-Zélande', icao: 'ZK', flagCode: 'nz' } as Country,
  { id: 145, name: 'Oman', icao: 'A4O', flagCode: 'om' } as Country,
  { id: 146, name: 'Ouganda', icao: '5X', flagCode: 'ug' } as Country,
  { id: 147, name: 'Ouzbékistan', icao: 'UK', flagCode: 'uz' } as Country,
  { id: 148, name: 'Pakistan', icao: 'AP', flagCode: 'pk' } as Country,
  { id: 149, name: 'Panama', icao: 'HP', flagCode: 'pa' } as Country,
  {
    id: 150,
    name: 'Papouasie-Nouvelle-Guinée',
    icao: 'P2',
    flagCode: 'pg',
  } as Country,
  { id: 151, name: 'Paraguay', icao: 'ZP', flagCode: 'py' } as Country,
  { id: 152, name: 'Pays-Bas', icao: 'PH', flagCode: 'nl' } as Country,
  { id: 153, name: 'Pérou', icao: 'OB', flagCode: 'pe' } as Country,
  { id: 154, name: 'Philippines', icao: 'RP', flagCode: 'ph' } as Country,
  { id: 155, name: 'Pologne', icao: 'SP', flagCode: 'pl' } as Country,
  {
    id: 156,
    name: 'Polynésie française (France)',
    icao: 'F-OH',
    flagCode: 'pf',
  } as Country,
  {
    id: 157,
    name: 'Porto Rico (États-Unis)',
    icao: 'N',
    flagCode: 'pr',
  } as Country,
  { id: 158, name: 'Portugal', icao: 'CR', flagCode: 'pt' } as Country,
  { id: 159, name: 'Qatar', icao: 'A7', flagCode: 'qa' } as Country,
  {
    id: 160,
    name: 'République centrafricaine',
    icao: 'TL',
    flagCode: 'cf',
  } as Country,
  {
    id: 161,
    name: 'République démocratique du Congo',
    icao: '9S',
    flagCode: 'cd',
  } as Country,
  {
    id: 162,
    name: 'République dominicaine',
    icao: 'HI',
    flagCode: 'do',
  } as Country,
  { id: 163, name: 'Tchéquie', icao: 'OK', flagCode: 'cz' } as Country,
  { id: 164, name: 'Roumanie', icao: 'YR', flagCode: 'ro' } as Country,
  {
    id: 165,
    name: 'Angleterre (Royaume-Uni)',
    icao: 'G',
    flagCode: 'gb-eng',
  } as Country,
  { id: 166, name: 'Russie', icao: 'RA', flagCode: 'ru' } as Country,
  { id: 167, name: 'Rwanda', icao: '9XR', flagCode: 'rw' } as Country,
  { id: 168, name: 'Sainte-Lucie', icao: 'J6', flagCode: 'lc' } as Country,
  {
    id: 169,
    name: 'Saint-Eustache (Pays-Bas)',
    icao: 'PJ',
    flagCode: 'bq',
  } as Country,
  {
    id: 170,
    name: 'Saint-Kitts-et-Nevis',
    icao: 'V4',
    flagCode: 'kn',
  } as Country,
  {
    id: 171,
    name: 'Saint-Martin (Pays-Bas)',
    icao: 'PJ',
    flagCode: 'sx',
  } as Country,
  {
    id: 172,
    name: 'Saint-Vincent-et-les-Grenadines',
    icao: 'J8',
    flagCode: 'vc',
  } as Country,
  { id: 173, name: 'Salvador', icao: 'YS', flagCode: 'sv' } as Country,
  { id: 174, name: 'Samoa', icao: '5W', flagCode: 'ws' } as Country,
  {
    id: 175,
    name: 'Samoa américaines (États-Unis)',
    icao: 'N',
    flagCode: 'as',
  } as Country,
  { id: 176, name: 'Sénégal', icao: '6V', flagCode: 'sn' } as Country,
  { id: 177, name: 'Serbie', icao: 'YU', flagCode: 'rs' } as Country,
  { id: 178, name: 'Seychelles', icao: 'S7', flagCode: 'sc' } as Country,
  { id: 179, name: 'Sierra Leone', icao: '9L', flagCode: 'sl' } as Country,
  { id: 180, name: 'Singapour', icao: '9V', flagCode: 'sg' } as Country,
  { id: 181, name: 'Slovaquie', icao: 'OM', flagCode: 'sk' } as Country,
  { id: 182, name: 'Slovénie', icao: 'S5', flagCode: 'si' } as Country,
  { id: 183, name: 'Somalie', icao: '6O', flagCode: 'so' } as Country,
  { id: 184, name: 'Soudan', icao: 'ST', flagCode: 'sd' } as Country,
  { id: 185, name: 'Soudan du Sud', icao: 'Z8', flagCode: 'ss' } as Country,
  { id: 186, name: 'Sri Lanka', icao: '4R', flagCode: 'lk' } as Country,
  { id: 187, name: 'Suède', icao: 'SE', flagCode: 'se' } as Country,
  { id: 188, name: 'Suisse', icao: 'HB', flagCode: 'ch' } as Country,
  { id: 189, name: 'Suriname', icao: 'PZ', flagCode: 'sr' } as Country,
  { id: 190, name: 'Syrie', icao: 'YK', flagCode: 'sy' } as Country,
  { id: 191, name: 'Tadjikistan', icao: 'EY', flagCode: 'tj' } as Country,
  { id: 192, name: 'Taïwan', icao: 'B', flagCode: 'tw' } as Country,
  { id: 193, name: 'Tanzanie', icao: '5H', flagCode: 'tz' } as Country,
  { id: 194, name: 'Tchad', icao: 'TT', flagCode: 'td' } as Country,
  { id: 195, name: 'Thaïlande', icao: 'HS', flagCode: 'th' } as Country,
  { id: 196, name: 'Timor oriental', icao: '4W', flagCode: 'tl' } as Country,
  { id: 197, name: 'Togo', icao: '5V', flagCode: 'tg' } as Country,
  { id: 198, name: 'Tonga', icao: 'A3', flagCode: 'to' } as Country,
  { id: 199, name: 'Trinité-et-Tobago', icao: '9Y', flagCode: 'tt' } as Country,
  { id: 200, name: 'Tunisie', icao: 'TS', flagCode: 'tn' } as Country,
  { id: 201, name: 'Turkménistan', icao: 'EZ', flagCode: 'tm' } as Country,
  { id: 202, name: 'Turquie', icao: 'TC', flagCode: 'tr' } as Country,
  { id: 203, name: 'Tuvalu', icao: 'T2', flagCode: 'tv' } as Country,
  { id: 204, name: 'Ukraine', icao: 'UR', flagCode: 'ua' } as Country,
  { id: 205, name: 'Uruguay', icao: 'CX', flagCode: 'uy' } as Country,
  { id: 206, name: 'Vanuatu', icao: 'YJ', flagCode: 'vu' } as Country,
  { id: 207, name: 'Venezuela', icao: 'YV', flagCode: 've' } as Country,
  { id: 208, name: 'Viêt Nam', icao: 'VN', flagCode: 'vn' } as Country,
  { id: 209, name: 'Yémen', icao: '7O', flagCode: 'ye' } as Country,
  { id: 210, name: 'Zambie', icao: '9J', flagCode: 'zm' } as Country,
  { id: 211, name: 'Zimbabwe', icao: 'Z', flagCode: 'zw' } as Country,
  {
    id: 212,
    name: 'Île Christmas (Australie)',
    icao: 'VH',
    flagCode: 'cx',
  } as Country,
  {
    id: 213,
    name: 'Irlande du Nord (Royaume-Uni)',
    icao: 'G',
    flagCode: 'gb-nir',
  } as Country,
  {
    id: 214,
    name: 'Écosse (Royaume-Uni)',
    icao: 'G',
    flagCode: 'gb-sct',
  } as Country,
  {
    id: 215,
    name: 'Pays de Galles (Royaume-Uni)',
    icao: 'G',
    flagCode: 'gb-wls',
  } as Country,
  { id: 216, name: 'Europe', icao: null, flagCode: 'eu' } as Country,
];
